In [27]:
import pandas as pd
import numpy as np
df = pd.read_csv("./user.csv")

In [28]:
df['compliment_count'] = df['compliment_more'] + df['compliment_profile'] + \
    df['compliment_cute'] + df['compliment_list'] + df['compliment_note'] + \
    df['compliment_plain'] + df['compliment_cool'] + df['compliment_funny'] +\
    df['compliment_writer'] + df['compliment_photos'] + df['compliment_hot']
df['votes'] = df['useful'] + df['funny'] + df['cool']

drop_list = ['more', 'profile', 'cute', 'list', 'note', 'plain', 'cool', 'funny', 'writer', 'photos', 'hot']
for i in range(11):
    drop_list[i] = 'compliment_' + drop_list[i]
print(drop_list)
    
df = df.drop(drop_list, axis=1)
df = df.drop(columns=['useful', 'funny', 'cool'])
df.head()

['compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list', 'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos', 'compliment_hot']


Unnamed: 0                 user_id       name  review_count  \
0     1817726  baysubsyBl7omYmSoAL_nQ  R Richard             2   
1     1927844  dqIFJVJVNb3srqK_vobrfw      Jenny            16   
2     1057397  XsEZazFrQDZhZqrC0t5sCw        Ann             3   
3     1513691  LdtFVKWwcO6cxsVDCBXqLA          W             5   
4     1073346  NUApbP2YOPnVsTPSvMsdxQ      Amber            11   

         yelping_since elite  \
0  2014-06-04 20:40:22   NaN   
1  2014-08-13 02:02:41   NaN   
2  2018-06-05 13:15:34   NaN   
3  2009-03-31 19:00:59   NaN   
4  2013-07-14 20:55:11   NaN   

                                             friends  fans  average_stars  \
0  YKVaewqx90wPPNCEfPTzUw, wc2vSdN_TdFR9BonSEHbRw...     0           4.50   
1                                               None     0           4.69   
2  Bj8gb3mKTnORVy1MC8FylQ, lwl_YWQ-1iXmcA-mHVG_jA...     0           1.67   
3                                               None     0           2.00   
4  j3GVN7VpDZ2I3_g332h3TQ, 3lKGcCwbxKB1bAgfCyVsLg...     0           4.17   

   compliment_count  votes  
0                 0      0  
1                 0      4  
2                 0      1  
3                 0      5  
4                 0      6

In [32]:
df['years_yelped'] = df['yelping_since'].apply(lambda x: x.split('-')[0])
df['years_yelped'] = 2022 - df['years_yelped'].astype(int)
df['num_friends'] = df['friends'].apply(lambda x: len(x.split(',')))
df['num_friends'] = np.where(df['friends']=='None', 0, df['num_friends'])

clean = df.drop(columns=['Unnamed: 0', 'user_id', 'name', 'yelping_since', 'elite', 'friends'])
normalized_clean=(clean-clean.mean())/clean.std()

<b>Euclidean</b>

In [33]:
from scipy.spatial.distance import pdist, squareform

distances = pdist(normalized_clean.values, metric='euclidean')
dist_matrix = squareform(distances)
print(dist_matrix)

[[0.         1.74131262 2.95260183 ... 1.9802489  5.75981585 1.80052097]
 [1.74131262 0.         2.83026597 ... 1.05617264 5.38547034 0.45937901]
 [2.95260183 2.83026597 0.         ... 3.58986946 5.98601343 2.91435075]
 ...
 [1.9802489  1.05617264 3.58986946 ... 0.         5.43327822 1.33479466]
 [5.75981585 5.38547034 5.98601343 ... 5.43327822 0.         5.72703042]
 [1.80052097 0.45937901 2.91435075 ... 1.33479466 5.72703042 0.        ]]


<b>Cosine</b>

In [34]:
distances = pdist(normalized_clean.values, metric='cosine')
dist_matrix = squareform(distances)
print(dist_matrix)

[[0.         0.921104   1.378236   ... 0.77348481 1.30949552 0.83834549]
 [0.921104   0.         1.6932503  ... 0.19854965 1.17675905 0.05675616]
 [1.378236   1.6932503  0.         ... 1.86949004 1.26483819 1.53236152]
 ...
 [0.77348481 0.19854965 1.86949004 ... 0.         1.03207663 0.38072901]
 [1.30949552 1.17675905 1.26483819 ... 1.03207663 0.         1.38880869]
 [0.83834549 0.05675616 1.53236152 ... 0.38072901 1.38880869 0.        ]]


<b>Mahalanobis</b>

In [35]:
distances = pdist(normalized_clean.values, metric='mahalanobis', VI=None)
dist_matrix = squareform(distances)
print(dist_matrix)

[[0.         1.81970392 2.81375282 ... 2.01878692 7.46110638 1.88497431]
 [1.81970392 0.         2.73212909 ... 1.2246816  6.96164399 0.5868891 ]
 [2.81375282 2.73212909 0.         ... 3.46699473 7.302729   2.86159005]
 ...
 [2.01878692 1.2246816  3.46699473 ... 0.         7.34467781 1.40860177]
 [7.46110638 6.96164399 7.302729   ... 7.34467781 0.         7.3760789 ]
 [1.88497431 0.5868891  2.86159005 ... 1.40860177 7.3760789  0.        ]]
